/* Generated by cbindgen from the hdfs-bridge crate — do not edit by hand.
 * The Rust definitions in hdfs-bridge/src/lib.rs are the source of truth;
 * a cargo build regenerates this file (see hdfs-bridge/build.rs). */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * No error; `Status` is left untouched on success, so this is only ever the
 * value the caller initialized it to.
 */
#define HDFS_OK 0

/**
 * Generic I/O / RPC failure.
 */
#define HDFS_ERR_IO 1

/**
 * Path does not exist.
 */
#define HDFS_ERR_NOT_FOUND 2

/**
 * Access denied.
 */
#define HDFS_ERR_PERMISSION 3

/**
 * Path already exists.
 */
#define HDFS_ERR_ALREADY_EXISTS 4

/**
 * Connect/RPC/SASL failure; the client may be stale.
 */
#define HDFS_ERR_CONNECTION 5

/**
 * Bad path / argument.
 */
#define HDFS_ERR_INVALID_ARGUMENT 6

/**
 * An HDFS client plus the shared Tokio runtime its operations run on.
 */
typedef struct hdfs_client_t hdfs_client_t;

/**
 * A streaming (optionally recursive, optionally parallel) directory listing.
 * A background task on the client's runtime walks the tree and feeds entries
 * through a bounded channel; [`BridgeListStream::next_batch`] drains it in
 * batches. Entries arrive in completion order (the walk schedules
 * depth-first, but parallel RPCs finish out of order), so no path order is
 * guaranteed.
 */
typedef struct hdfs_list_stream_t hdfs_list_stream_t;

/**
 * An open file reader; see [`BridgeClient`] for the runtime coupling.
 */
typedef struct hdfs_reader_t hdfs_reader_t;

/**
 * An open file writer; see [`BridgeClient`] for the runtime coupling.
 */
typedef struct hdfs_writer_t hdfs_writer_t;

/**
 * Result of a fallible call. On success `code == HDFS_OK` and `msg == NULL`.
 * On failure `code` is the category and `msg` is an owned, NUL-terminated
 * message that the caller must free with `hdfs_bridge_free_string`. Callers
 * must initialize the struct to `{HDFS_OK, NULL}` before each call; the
 * bridge only writes it on failure.
 */
typedef struct hdfs_status_t {
  /**
   * One of the `HDFS_OK` / `HDFS_ERR_*` categories.
   */
  int32_t code;
  char *msg;
} hdfs_status_t;

/**
 * Metadata for a single path. `mtime` is epoch milliseconds.
 */
typedef struct hdfs_file_info_t {
  int64_t length;
  bool is_dir;
  uint64_t mtime;
} hdfs_file_info_t;

/**
 * One entry in a listing/glob result. `path`, `owner` and `group` are owned
 * C strings (`path` is scheme-less, e.g. "/a/b"); free the whole entry with
 * `hdfs_bridge_free_dir_entries`. `replication` and `block_size` are `-1`
 * when not applicable (HDFS leaves them unset for directories);
 * `mtime`/`atime` are epoch milliseconds.
 */
typedef struct hdfs_dir_entry_t {
  char *path;
  bool is_dir;
  int64_t length;
  uint64_t mtime;
  uint64_t atime;
  char *owner;
  char *group;
  uint16_t permission;
  int32_t replication;
  int64_t block_size;
} hdfs_dir_entry_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a C string previously returned by the bridge (status messages, etc.).
 */
void hdfs_bridge_free_string(char *s);

/**
 * Connect to HDFS. `url` (e.g. `hdfs://namenode:8020`), `config_dir`, and
 * `user` are all optional (pass null or empty to omit).
 */
struct hdfs_client_t *hdfs_bridge_connect(const char *url,
                                          const char *config_dir,
                                          const char *user,
                                          struct hdfs_status_t *status);

void hdfs_bridge_free_client(struct hdfs_client_t *client);

/**
 * Fill `out` with metadata for `path`. Returns 0 on success, -1 on error
 * (including not-found; check `status->code`).
 */
int32_t hdfs_bridge_get_file_info(struct hdfs_client_t *client,
                                  const char *path,
                                  struct hdfs_file_info_t *out,
                                  struct hdfs_status_t *status);

struct hdfs_reader_t *hdfs_bridge_open(struct hdfs_client_t *client,
                                       const char *path,
                                       struct hdfs_status_t *status);

void hdfs_bridge_close_reader(struct hdfs_reader_t *reader);

/**
 * Total file length (cached on the reader, no RPC).
 */
int64_t hdfs_bridge_file_size(struct hdfs_reader_t *reader);

/**
 * Read exactly `len` bytes into `buf` starting at `offset`. The caller must
 * ensure `offset + len <= file_size`. Returns the number of bytes read
 * (`len`) on success, or -1 on error. Thread-safe across concurrent calls on
 * the same reader.
 */
int64_t hdfs_bridge_read_range(struct hdfs_reader_t *reader,
                               uint8_t *buf,
                               int64_t len,
                               uint64_t offset,
                               struct hdfs_status_t *status);

/**
 * Create a file for writing. `overwrite` controls whether an existing file is
 * replaced; missing parent directories are always created.
 */
struct hdfs_writer_t *hdfs_bridge_create(struct hdfs_client_t *client,
                                         const char *path,
                                         bool overwrite,
                                         struct hdfs_status_t *status);

/**
 * Append `len` bytes from `buf` to the file. Returns bytes written, or -1.
 * A success is always a full write of `len` bytes.
 */
int64_t hdfs_bridge_write(struct hdfs_writer_t *writer,
                          const uint8_t *buf,
                          int64_t len,
                          struct hdfs_status_t *status);

/**
 * Flush and close the writer, consuming the handle. Returns 0 or -1. The
 * handle must not be used afterwards regardless of the result.
 */
int32_t hdfs_bridge_close_writer(struct hdfs_writer_t *writer, struct hdfs_status_t *status);

/**
 * Start a streaming listing of `path`. When `recursive` is true the whole
 * subtree is walked, with `max_parallelism` bounding the number of concurrent
 * listing RPCs (values <= 1 list one directory at a time). Opening never
 * fails; errors (including not-found) surface on the first `next` call.
 * Unless `include_hidden`, entries named with a leading `.` or `_` are
 * neither returned nor descended into (`path` itself is exempt). With
 * `skip_permission_errors`, subtrees below `path` the caller may not list
 * are pruned instead of failing the walk; errors on `path` itself always
 * surface.
 */
struct hdfs_list_stream_t *hdfs_bridge_list_stream_open(struct hdfs_client_t *client,
                                                        const char *path,
                                                        bool recursive,
                                                        int32_t max_parallelism,
                                                        bool skip_permission_errors,
                                                        bool include_hidden);

/**
 * Start a streaming glob of `pattern`: matched entries — files and
 * directories — are returned themselves (no descent into matched
 * directories). Supports `*`, `?`, `[...]` classes, `\` escapes, `{a,b}`
 * alternation, and `**` as a whole component matching zero or more levels.
 * `max_parallelism` bounds the number of concurrent listing RPCs. Returns
 * null with a non-OK status for an invalid pattern; a pattern matching
 * nothing yields an empty stream, and other errors surface on `next`.
 * Unless `include_hidden`, names with a leading `.` or `_` only match
 * components that spell that character out literally (`_temporary`, `_*`),
 * and `**` never matches or descends into them. With
 * `skip_permission_errors`, directories below the pattern's literal root the
 * caller may not list are pruned instead of failing the walk.
 */
struct hdfs_list_stream_t *hdfs_bridge_glob_stream_open(struct hdfs_client_t *client,
                                                        const char *pattern,
                                                        int32_t max_parallelism,
                                                        bool skip_permission_errors,
                                                        bool include_hidden,
                                                        struct hdfs_status_t *status);

/**
 * Fetch the next batch of entries (at most `max_entries`), blocking until at
 * least one is available. Returns null with `*out_count == 0` and an OK
 * status when the listing is exhausted, or null with a non-OK status on
 * error. Streams are not thread-safe; drive each from one thread at a time.
 */
struct hdfs_dir_entry_t *hdfs_bridge_list_stream_next(struct hdfs_list_stream_t *stream,
                                                      int32_t max_entries,
                                                      int32_t *out_count,
                                                      struct hdfs_status_t *status);

void hdfs_bridge_list_stream_free(struct hdfs_list_stream_t *stream);

/**
 * Free an array of `DirEntry` returned by glob/list, including each path.
 */
void hdfs_bridge_free_dir_entries(struct hdfs_dir_entry_t *entries, int32_t count);

/**
 * Stat a single `path`, returning a one-element `DirEntry` array (freed with
 * `hdfs_bridge_free_dir_entries(ptr, 1)`). Returns null on error (including
 * not-found; check `status->code`). This is the rich counterpart to
 * `hdfs_bridge_get_file_info`, which stays lean for the internal hot path.
 */
struct hdfs_dir_entry_t *hdfs_bridge_stat(struct hdfs_client_t *client,
                                          const char *path,
                                          struct hdfs_status_t *status);

/**
 * Create directory `path` (and any missing parents) with mode 0o755.
 */
int32_t hdfs_bridge_mkdirs(struct hdfs_client_t *client,
                           const char *path,
                           struct hdfs_status_t *status);

/**
 * Delete `path`. `recursive` must be true to remove a non-empty directory.
 * A server response of "false" (nothing deleted) is reported as not-found.
 */
int32_t hdfs_bridge_delete(struct hdfs_client_t *client,
                           const char *path,
                           bool recursive,
                           struct hdfs_status_t *status);

/**
 * Rename `src` to `dst`.
 */
int32_t hdfs_bridge_rename(struct hdfs_client_t *client,
                           const char *src,
                           const char *dst,
                           bool overwrite,
                           struct hdfs_status_t *status);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
